export {
  BROWSER_HARNESS_CAPABILITY,
  BROWSER_HARNESS_ID,
  HARNESS_TASKS,
  BROWSER_HARNESS_CAPABILITY as WORKFLOW_AUTHORING_CAPABILITY,
  BROWSER_HARNESS_CAPABILITY as INTENT_CLASSIFICATION_CAPABILITY,
} from "@ecp/harnesses-browser"
