export {
  BROWSER_WORKFLOW_AUTHORING_CAPABILITY as WORKFLOW_AUTHORING_CAPABILITY,
  BROWSER_INTENT_CLASSIFICATION_CAPABILITY as INTENT_CLASSIFICATION_CAPABILITY,
} from "../harnesses/harness-ids.js"
